- name: Install apache
  apt:
    name: apache2
    state: present

- name: Inject site config
  template:
    src: apache.j2
    dest: "/etc/apache2/sites-available/{{ inventory_hostname }}.{{ domain }}.conf"
    owner: root
    group: root
    mode: 0644

- name: Create ssl directory
  file:
    path: "/etc/apache2/ssl"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Create private ssl directory
  file:
    path: "/etc/apache2/ssl/private"
    state: directory
    owner: root
    group: root
    mode: 0700

- name: Copy cert
  copy:
    src: "{{ inventory_hostname }}.{{ domain }}.pem"
    dest: "/etc/apache2/ssl/{{ inventory_hostname }}.{{ domain }}.pem"
    owner: root
    group: root
    mode: 0644

- name: Copy key
  copy:
    src: "{{ inventory_hostname }}.{{ domain }}.key"
    dest: "/etc/apache2/ssl/private/{{ inventory_hostname }}.{{ domain }}.key"
    owner: root
    group: root
    mode: 0600

- name: Enable mod_rewrite
  apache2_module:
    name: rewrite
    state: present
  notify: restart_apache

- name: Enable ssl
  apache2_module:
    name: ssl
    state: present
  notify: restart_apache

- name: Enable site config
  command: "/usr/sbin/a2ensite {{ inventory_hostname }}.{{ domain }}.conf"
  args:
    creates: "/etc/apache2/sites-enabled/{{ inventory_hostname }}.{{ domain }}.conf"
  notify: reload_apache

- name: Disable default apache config
  command: /usr/sbin/a2dissite 000-default.conf
  args:
    removes: "/etc/apache2/sites-enabled/000-default.conf"
  notify: reload_apache

- name: Ensure apache is started and enabled
  service:
    name: apache2
    state: started
    enabled: yes
