- name: Install apache
  apt:
    name: apache2
    state: present

- name: Enable mod_rewrite
  apache2_module:
    name: rewrite
    state: present
    notify: restart_apache

- name: Enable ssl
  apache2_module:
    name: ssl
    state: present
    notify: restart_apache

- name: Inject site config
  template:
    src: apache.j2
    dest: /etc/apache2/sites-available/kansai-ssl.conf
    owner: root
    group: root
    mode: 0644

- name: Enable site config
  shell: /usr/sbin/a2ensite kansai-ssl.conf
  notify: reload_apache

- name: Disable default apache config
  shell: /usr/sbin/a2dissite 000-default.conf
  notify: reload_apache
