
test_machines:
  hosts:
    ubuntu-test:

production_machines:
  hosts:
    ansible:
    bookstack:
    gitea:
    ombi:
    nginx:
    plex:
    radarr:
    sonarr:
    tautulli:
    unifi:
    vault:

all:
  children:
    test_machines:
    production_machines: