
new_machines:
  hosts:

test_machines:
  hosts:
    ubuntu-test:

hypervisors:
  hosts:
    wakayama:
    arashiyama:

production_machines:
  hosts:
    ansible:
    bookstack:
    gitea:
    ombi:
    nginx:
    plex:
    proxy:
    radarr:
    sonarr:
    tautulli:
    unifi:
    vault:
  children:
    hypervisors:

apache_servers:
  hosts:
    bookstack:

docker_servers:
  hosts:
    ombi:
    radarr:
    sonarr:

all:
  children:
    test_machines:
    production_machines:
