
new_machines:
  hosts:

test_machines:
  hosts:
    ubuntu-test:

production_machines:
  hosts:
    ansible:
    bookstack:
    gitea:
    ombi:
    nginx:
    plex:
    proxy:
    radarr:
    sonarr:
    tautulli:
    unifi:
    vault:

apache_servers:
  hosts:
    bookstack:

all:
  children:
    test_machines:
    production_machines:
