# This was all replaced once the authorized_key module was discovered
# Inject client pubkeys
- name: Create ssh directory
  file:
    path: "/home/{{ user_name }}/.ssh"
    state: directory
    recurse: yes
    owner: "{{ user_name }}"
    group: "{{ user_group }}"
    mode: 0700

- name: Create authorized_keys file
  file:
    path: "/home/{{ user_name }}/.ssh/authorized_keys"
    state: touch
    owner: "{{ user_name }}"
    group: "{{ user_group }}"
    mode: 0600

- name: Inject SSH keys
  lineinfile:
    path: "/home/{{ user_name }}/.ssh/authorized_keys"
    line: "{{ item }}"
  with_items:
    - "{{ wsl_pubkey }}"
    - "{{ spectre_pubkey }}"


# Get vault token
- name: Vault auth
  uri:
    url: "{{ vault_addr }}/v1/auth/cert/login"
    method: POST
    client_cert: ansible.kansai.pem
    client_key: ansible.kansai.key
    body: "{ 'name': 'ansible' }"
    return_content: yes
  register: vault_token_response

- name: Vault token verification
  debug:
    msg: "{{ vault_token_response.auth.client_token }}"

- name: Get Vault secret
  uri:
    url: "{{ vault_addr }}/v1/kv/data/ansible"
    method: GET
    headers:
      X-Vault-Token: "{{ vault_token_response.auth.client_token }}"
    status_code: 200
    return_content: yes
  register: secret_response

- name: Vault secret verification
  debug:
    msg: "{{ secret_response.data.data.data }}"
