# Create local user
- name: Create casey group
  group:
    name: "{{ user_group }}"
    state: present

- name: Create casey user
  user:
    name: "{{ user_name }}"
    password: "{{ user_password | password_hash('sha512', user_password_salt) }}"
    shell: /bin/bash
    home: "/home/{{ user_name }}"
    create_home: true
    group: "{{ user_group }}"
    groups:
      - sudo
    state: present

# Inject client pubkeys
- name: Create ssh directory
  file:
    path: "/home/{{ user_name }}/.ssh"
    state: directory
    recurse: yes
    owner: "{{ user_name }}"
    group: "{{ user_group }}"
    mode: 0700

- name: Create authorized_keys file
  file:
    path: "/home/{{ user_name }}/.ssh/authorized_keys"
    state: touch
    owner: "{{ user_name }}"
    group: "{{ user_group }}"
    mode: 0600

- name: Inject SSH keys
  lineinfile:
    path: "/home/{{ user_name }}/.ssh/authorized_keys"
    line: "{{ item }}"
  with_items:
    - "{{ wsl_pubkey }}"
    - "{{ spectre_pubkey }}"

# Configure user environment as desired
- name: Copy .bash-aliases
  copy:
    src: ".bash-aliases"
    dest: "/home/{{ user_name }}/.bash-aliases"

# Update + upgrade Ubuntu
- name: apt update
  apt:
    update_cache: yes
    cache_valid_time: 3600
    upgrade: dist

# Install desired packages
- name: Install vim
  apt:
    name:
     - "vim"
     - "htop"
     - "curl"
     - "jq"
    state: present

# Prep for installing local root CA
- name: Install ca-certificates package
  apt:
    name: "ca-certificates"
    state: present

- name: Create cert directory
  file:
    path: "{{ cert_path }}"
    state: "directory"
    recurse: yes
    owner: "root"
    group: "root"

# Copy the root CA cert and update cert store so it is trusted
- name: Copy cert
  copy:
    src: "{{ cert_file }}"
    dest: "{{ cert_path }}/{{ cert_file }}"
  notify:
    - update-ca-certificates


