# Create local user
- name: Create casey group
  group:
    name: "{{ user_group }}"
    state: present

- name: Create casey user
  user:
    name: "{{ user_name }}"
    password: "{{ user_password | password_hash('sha512', user_password_salt) }}"
    shell: /bin/bash
    home: "/home/{{ user_name }}"
    create_home: true
    group: "{{ user_group }}"
    groups:
      - sudo
    state: present

- name: Inject SSH keys
  authorized_key:
    user: casey
    state: present
    key: "{{ item }}"
  with_file:
    - "{{ wsl_pubkey_path }}"
    - "{{ spectre_pop_pubkey_path }}"
    - "{{ yubikey_pubkey_path }}"
    - "{{ galago_pro_pubkey_path }}"

# Configure user environment as desired
- name: Copy .bash_aliases
  copy:
    src: ".bash_aliases"
    dest: "/home/{{ user_name }}/.bash_aliases"

# Update + upgrade Ubuntu
- name: apt update + upgrade-dist
  apt:
    update_cache: yes
    cache_valid_time: 3600
    upgrade: dist

# Install desired packages
- name: Install packages
  apt:
    name:
     - "vim"
     - "htop"
     - "curl"
     - "jq"
     - "ca-certificates"
    state: present

# Prep for installing local root CA
- name: Create cert directory
  file:
    path: "{{ cert_path }}"
    state: "directory"
    recurse: yes
    owner: "root"
    group: "root"

# Copy the root CA cert and update cert store so it is trusted
- name: Copy cert
  copy:
    src: "{{ cert_file }}"
    dest: "{{ cert_path }}/{{ cert_file }}"
  notify:
    - update-ca-certificates


